version: '3'
services:
  postgres:
    image: postgres:11.2
    hostname: db-orcamento
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /media/danilo/Parangoamico Tirimico Aro/Projetos/orcamento-api/docker/postgres/data:/var/lib/postgresql/data
      - ./postgres/config/init-db.sh://docker-entrypoint-initdb.d/init-db.sh
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    volumes:
      - /media/danilo/Parangoamico Tirimico Aro/Projetos/orcamento-api/docker/pgadmin/data:/var/lib/pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped


